spring:
  datasource:
    url: jdbc:h2:mem:testdbss
#      url: jdbc:h2:file:~/testdb1s
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true  # SQL 실행 로그 출력
  h2:
    console:
      enabled: true  # H2 콘솔 활성화 (웹 브라우저에서 접근 가능)
      path: /h2-console  # H2 콘솔 URL 경로
jwt:
  issuer: aa@gmail.com
  secret_key: sb-study

kakao:
  client-id: 7c1abe679fd03dfbdbf3ab027875f18b
  redirect-url: http://localhost:8080/auth/login/kakao